name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Setup node env
        uses: actions/setup-node
        with:
          node-version: 18.17.1
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Lint
        run: npm run lint